### ISSUE TITLE
Не воркает

### ISSUE THREAD

**Issue by zaninvova** [GyverLibs/GParser#2]
Код
`#include <GParser.h>

void setup() {
  Serial.begin(9600);
}
 
void loop() {
  if(Serial.available()){
  char strt;
  strt = Serial.read();
  GParser data(strt, ',');
  int am = data.split();
  Serial.println(am);
  for (byte i = 0; i < am; i++) Serial.println(data[i]);
  }

}`
а в порт выходит мусор из квадратиков

**Comment by GyverLibs** [comment]
всё правильно, потому что ты передал один символ, см. пример
