### ISSUE TITLE
Разбивка текста на части по разелителю

### ISSUE THREAD

**Issue by Stass48** [GyverLibs/GParser#4]
Приветствую!
Вы не поверите, не работает. Я понимаю, что библиотека устарела, но она устарела не так давно. В общем, к сути.
Делим текст по пробелам:

```
GParser dirTextParser(dirText, ' ');
int parts = dirTextParser.split();
char firstLine[500];
char firstLineTest[500];
strcpy(firstLineTest, dirTextParser[0]);
strcpy(firstLine, dirTextParser[0]);
```

В переменной firstLineTest все хорошо. В переменной firstLine абракадабра. То есть, работает, если считывать dirTextParser[0] один раз.

**Comment by GyverLibs** [comment]
Вы не поверите, всё работает, в том числе приложенный код. Скорее всего проблема в закончившейся оперативной памяти, 2*500 байт это не шутки
