### ISSUE TITLE
Функция split()

### ISSUE THREAD

**Issue by Stass48** [GyverLibs/GParser#5]
Здравствуйте! Не спешите закрывать тему. У меня не работает. Отсылка к:

https://github.com/GyverLibs/GParser/issues/4

Вы написали об оперативной памяти, но у меня не pro mini. Даже для 2560 один килобайт памяти это вполне посильно. Но у меня не та и не другая плата, у меня Teensy 4.1. Вы думаете там закончилась оперативная память? Я сомневаюсь. Я не с пассивной агрессией, я по факту) К тому же, я уменьшил объем переменных с 500 до 20 байт, это не решило проблему. К тому же, минимальные изменения в коде приводят к перезагрузке платы. Я не знаю почему это происходит.
Я добавил всего лишь при объявлении тех двух переменных присвоение им "" и плата стала уходить в перезагрузку. Я добавил объем переменных с 20 до 50 байт. Плата перестала уходить в перезагрузку, но текст стал коверкаться по-другому.
Я не обвиняю вас ни в коем случае в кривой библиотеке или еще в чем-то подобном. Наоборот, я благодарен и было бы не плохо если бы она пригодилась в моем проекте. Но я сейчас ищу баг и не могу его найти. В своем коде я использую только вполне безобидные функции. Я вообще понятия не имею как мой код может приводить к такому поведению.
Если можете помочь, буду благодарен. Может у вас есть какие-то хотя бы догадки, почему так может происходить.

**Comment by GyverLibs** [comment]
- работают ли примеры из библиотеки?
- можно взглянуть на минимальный код, который приводит к багу?

**Comment by Stass48** [comment]
Да, конечно. Но по ходу, я уже нашел причину.

Вот код:

void DisplayDirection(const char* _directionText, const uint16_t _textColor) {
    char directionText[500] = "";
    strcpy(directionText, _directionText);
    GParser dirTextParser(directionText, ' ');
    int parts = dirTextParser.split();
    Serial.print(dirTextParser[0]);
    Serial.print(dirTextParser[0]);
    Serial.print(sizeof(_directionText));
}

Вот он уже работает. Как было когда не работало? Вот так:

char directionText[sizeof(_directionText)] = "";

Я решил создать дубликат входящего текста, чтобы не вносить изменения в исходный текст, так как функция split меняет разделители на NULL. Однако, мне ведь нужно знать размер в байтах входящего текста, чтобы создать переменную для дубликата нужного размера. Я решил это сделать через sizeof(). В отчаянии и не зная, где искать баг, я решил вписать 500 вместо sizeof(_directionText) чтобы уж наверняка хватило. Ну и что. Ребуты прекратились. В порт выводится нормальный текст. Копировать в переменные и выводить этот текст на дисплей я еще не пробовал, но, думаю, оно будет работать. Очень похоже, что причина не в библиотеке. К слову, 

Serial.print(sizeof(_directionText));

выводит в порт 4. 4 байта, это очень мало. Я так понимаю, это размер указателя, но не текста.

Сейчас чешу репу и думаю, а чем же взять размер тогда текста этого?

Как решу это, проверю свой код, если все ок и будет работать, то тему можно закрывать. Если вы можете подсказать как это сделать, то буду очень благодарен :)

**Comment by GyverLibs** [comment]
Длину строки в Си определяют при помощи strlen()

**Comment by Stass48** [comment]
Это если латиница, но у меня там кириллица. Хотя... Стоп... Оно же в байтах и вернет. Логично. Сейчас попробую, отпишу. Спасибо)

**Comment by GyverLibs** [comment]
Да, в байтах. Корректную длину строки в символах с кириллицей можно получить утилитой из библиотеки StringUtils у меня на гите

**Comment by Stass48** [comment]
Проверил) Да, работает. Текст выводит корректно. strlen возвращает 107, что более похоже на правду.
Еще пару вопросов. 
strlen это длина строки с учетом NULL?
Насколько критично присваивать массиву char = ""?

**Comment by GyverLibs** [comment]
strlen это количество читаемых символов, без учёта нуля. Инициализировать char[] строкой "" можно и нужно, для программы это корректная "пустая" строка. Если не инициализировать - при вызове strlen счётчик может уйти далеко за пределы строки куда то в память

**Comment by GyverLibs** [comment]
Поговорку придумал - век живи - век учи с~ь~и :)

**Comment by Stass48** [comment]
Тогда получается, что strlen в моем случае тоже не корректное решение... Мне вообще не понятно, что оно выводит. Я не понимаю тогда как мой код теперь вообще работает, если оно возвращает символы без нуля в конце.
У меня там вообще кириллица. То есть, я думал, что оно возвращает количество байт в переменной. По сути, так как латинские символы в Юникоде занимают один байт, то по сути strlen возвращает количество латинских символов в строке. Но ведь правда же, что без нуля в конце.
Так вот у меня тогда вопрос к вам, как к профессионалу. Как же мне создать копию строки? Точнее, как правильно определить ее размер для новой переменной? Вот так?

```
void DisplayDirection(const char* _directionText, const uint16_t _textColor) {
   char dirText[strlen(_directionText) + 1];
}
```

То есть, нужно добавлять еще один байт для нулевого символа? Так правильно или есть еще какие-то нюансы?
Я пересмотрел кучу ваших видео и перечитал информацию в Интернете. Тот код, для подсчета кириллицы я даже разобрался как работает. Хотя там без 100 грамм не разберешься) Я и не знал, что Си так умеет)
В общем, подскажите мне уже по этой строке пожалуйста, чтобы я точно успокоился.

**Comment by GyverLibs** [comment]
> нужно добавлять еще один байт для нулевого символа?

Конечно! При копировании валидной строки функция strcpy добавит null в конце, поэтому буфер обязан быть на 1 больше. Иначе программа запишет этот 0 туда, где он может что то сломать. Также есть функция strdup, она создаёт копию строки но уже в динамической памяти (в heap). Если это возможно, лучше выделять массив-буфер и копировать через strcpy/memcpy/ctrncpy

**Comment by GyverLibs** [comment]
Видео у меня довольно ознакомительные, более полная информация в текстовых уроках
https://alexgyver.ru/lessons/

**Comment by Stass48** [comment]
Воу, там действительно много полезного материала. Спасибо огромное. По поводу остального.
Я пока не хочу далеко лезть. Пока что в моей голове есть понимание, что создал переменную, записал в нее значение, использовал. После выполнения функции оно все выгрузилось. Вот у меня вопрос пока что.

Это точно правильно?

char dirText[strlen(_directionText) + 1];

Я уже боюсь всего. Проект ответственный. Я написал перед этим без добавления единицы и оно работало. Но, как я понимаю, оно куда-то ноль записало куда не надо... В общем, скажите мне по этой строке, если вам не сложно.

**Comment by GyverLibs** [comment]
Для копирования строки - да, обязательно нужно создавать буфер на 1 больше, чем реальная длина строки

**Comment by Stass48** [comment]
Огромное спасибо)
ИИ с вами тоже согласен 😂

![image](https://github.com/GyverLibs/GParser/assets/143362590/77671b52-850c-4ef3-bb3f-51b8f122fe9e)

Думаю, теперь тему можно закрывать. Еще раз огромное спасибо за ответы и уделенное время 😌
