### ISSUE TITLE
Разделение текста по переходу на новую строку

### ISSUE THREAD

**Issue by Stass48** [GyverLibs/GParser#6]
Здравствуйте!
Столкнулся с еще одной проблемой. Оказывается, переход на новую строку не так прост. Я делаю разделение по символу '\n', но переход на новую строку в текстовом файле, написанном в Блокноте подразумевает два символа \r \n. В итоге, у меня в конце каждой строки вылазит этот символ, который вообще не нужен.

**Comment by GyverLibs** [comment]
привет, ну значит обрабатывать-пропускать его дополнительно у себя в программе, это не проблема

**Comment by Stass48** [comment]
Да уже решил. В строках где нужно, на место этого символа пишу NULL, вроде работает)
Я думал, может библиотека как-то это поддерживает.

**Comment by GyverLibs** [comment]
Библиотека просто делает разделение **по символу**
