### ISSUE TITLE
Ошибка при компиляции примера test.ino (функция split)

### ISSUE THREAD

**Issue by SkywalkerJEDI** [GyverLibs/GParser#7]
При использовании функции split возникает ошибка при компиляции. Попробовал скомпилировать examples/test/test.ino - ошибка аналогичная:

C:\Users\User\AppData\Local\Temp\ccwuZChb.ltrans0.ltrans.o: In function `split':
d:\Documents\Arduino\libraries\GParser\src/GParser.h:68: undefined reference to `operator new[](unsigned int)'
C:\Users\User\AppData\Local\Temp\ccwuZChb.ltrans0.ltrans.o: In function `GParser::clear() [clone .isra.0]':
d:\Documents\Arduino\libraries\GParser\src/GParser.h:49: undefined reference to `operator delete[](void*)'
collect2.exe: error: ld returned 1 exit status

**Comment by GyverLibs** [comment]
для работы библиотеки требуется, чтобы компилятор знал реализацию `new` и `delete`. Нужно запускать библиотеку внутри Arduino фреймворка или использовать другой компилятор

**Comment by SkywalkerJEDI** [comment]
Библиотека запускается в нативной Arduino IDE.
![IMG_2024_12_18_20_23_21_456394449433811189817](https://github.com/user-attachments/assets/d6abedd5-3014-434c-8aa3-4f68a7a21774)

**Comment by GyverLibs** [comment]
в таком случае не знаю
![image](https://github.com/user-attachments/assets/1cff83ee-9a9b-4519-bc45-4b79e64a4c85)
